// web-study/three-all/03reactthreedemo/src/App.jsx
import { useEffect } from "react"
import * as THREE from "three"

function App() {
  useEffect(() => {
    // 场景
    const scene = new THREE.Scene()
    // 创建相机
    const camera = new THREE.PerspectiveCamera(
      45,
      window.innerWidth / window.innerHeight,
      0.1,
      1000
    );
    // 创建渲染器
    const renderer = new THREE.WebGLRenderer();
    renderer.setSize(window.innerWidth, window.innerHeight)
    document.body.appendChild(renderer.domElement)

    // 创建几何体
    const geometry = new THREE.BoxGeometry(1, 1, 1);

    // 创建材质
    const material = new THREE.MeshBasicMaterial({ color: "#f60" });
    // 创建网格
    const cube = new THREE.Mesh(geometry, material);
    // 把网格添加到场景中
    scene.add(cube)

    // 设置相机位置
    camera.position.z = 5
    camera.lookAt(0, 0, 0)

    // 渲染函数
    function animate() {
      requestAnimationFrame(animate)
      // 旋转
      cube.rotation.x += 0.01
      cube.rotation.y += 0.01
      // 渲染
      renderer.render(scene, camera)
    }

    animate()
  }, [])
  return (
    <>
    </>
  )
}

export default App

// web-study/three-all/02vuethreedemo/src/App.vue
<script setup>
 import * as THREE from "three"
// 场景
const scene = new THREE.Scene()
// 创建相机
const camera = new THREE.PerspectiveCamera(
    45,
    window.innerWidth / window.innerHeight,
    0.1,
    1000
);
// 创建渲染器
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight)
document.body.appendChild(renderer.domElement)

// 创建几何体
const geometry = new THREE.BoxGeometry(1, 1, 1);

// 创建材质
const material = new THREE.MeshBasicMaterial({color: "#f60"});
// 创建网格
const cube = new THREE.Mesh(geometry, material);
// 把网格添加到场景中
scene.add(cube)

// 设置相机位置
camera.position.z = 5
camera.lookAt(0, 0, 0)

// 渲染函数
function animate() {
    requestAnimationFrame(animate)
    // 旋转
    cube.rotation.x += 0.01
    cube.rotation.y += 0.01
    // 渲染
    renderer.render(scene, camera)
}

animate()
</script>

<template>
</template>
<style>


</style>
